# Get more info on the settings.yaml here:https://github.com/apps/settings
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: glossary

  # A short description of the repository that will show up on GitHub
  description: The CNCF Cloud Native Glossary Project aims to define cloud native concepts in clear and simple language, making them accessible to anyone â€”  whether they have a technical background or not (https://glossary.cncf.io).

  # A URL with more information about the repository
  homepage: https://glossary.cncf.io/
  
  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Chairs
  - username: caniszczyk
    permission: admin

  - username: jasonmorgan
    permission: admin

  - username: CathPag
    permission: maintain
    
  - username: seokho-son
    permission: admin
  
  - username: jihoon-seo
    permission: maintain

  - username: iamNoah1
    permission: maintain  
  
  # English approvers (approver for all files in repository)

  

  # Localization approvers
  # l10n ko approvers
  # Note: seokho-son is both Maintainer (maintain) and Korean approver (push)
  # Note: jihoon-seo is both English approver (push) and Korean approver (push)
  - username: Eviekim
    permission: push

  - username: yunkon-kim
    permission: push

  # l10n pt approvers
  - username: edsoncelio
    permission: push

  - username: brunoguidone
    permission: push

  - username: jessicalins
    permission: push

  - username: MrErlison
    permission: push

  # l10n hi approvers
  - username: Garima-Negi
    permission: push

  - username: sayantani11
    permission: push

  - username: anubha-v-ardhan
    permission: push

  - username: jayesh-srivastava
    permission: push

  # l10n de approvers
  # Note: CathPag is both Maintainer (maintain) and de approver (push)
  # Note: iamNoah1 is both English approver (push) and de approver (push)
  - username: DaveVentura
    permission: push

  # l10n it approvers
  - username: fsbaraglia
    permission: push

  - username: meryem-ldn
    permission: push

  - username: annalisag-spark
    permission: push

  - username: sistella
    permission: push

  # l10n ar approvers
  - username: TarekMSayed
    permission: push

  - username: same7ammar
    permission: push

  - username: AShabana
    permission: push

  - username: arezk84
    permission: push

  # l10n bn approvers
  - username: mitul3737
    permission: push

  - username: Mouly22
    permission: push

  - username: ikramulkayes
    permission: push
    
  - username: Imtiaz1234
    permission: push
    
  # l10n es approvers
  - username: raelga
    permission: push
    
  - username: electrocucaracha
    permission: push

  - username: krol3
    permission: push

  - username: 92nqb
    permission: push

  # l10n zh approvers
  - username: hanyuancheung
    permission: push

  - username: Jacob953
    permission: push

  - username: Rocksnake
    permission: push

  - username: Submarinee
    permission: push

  # l10n fr approvers
  - username: huats
    permission: push

  - username: fydrah
    permission: push

  - username: Krast76
    permission: push

  # l10n ur approvers
  - username: Saim-Safdar
    permission: push

  - username: waleed318
    permission: push


branches:

  # Default branch of this repository for configurations and English contents
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # En approvers (including Chairs)
        users:
         - caniszczyk
         - jasonmorgan
         - CathPag
         - seokho-son
         - iamNoah1
         - jihoon-seo
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for Korean contents only
  - name: dev-ko
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # Ko approvers
        users:
         - seokho-son
         - Eviekim
         - jihoon-seo
         - yunkon-kim
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for pt contents only
  - name: dev-pt
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # pt approvers
        users:
         - edsoncelio
         - brunoguidone
         - jessicalins
         - MrErlison
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for hi contents only
  - name: dev-hi
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # hi approvers
        users:
         - Garima-Negi
         - sayantani11
         - anubha-v-ardhan
         - jayesh-srivastava
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for de contents only
  - name: dev-de
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # de approvers
        users:
         - iamNoah1
         - DaveVentura
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for it contents only
  - name: dev-it
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # it approvers
        users:
         - fsbaraglia
         - meryem-ldn
         - annalisag-spark
         - sistella
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for ar contents only
  - name: dev-ar
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # ar approvers
        users:
         - TarekMSayed
         - same7ammar
         - AShabana
         - arezk84
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for bn contents only
  - name: dev-bn
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # bn approvers
        users:
         - mitul3737
         - Mouly22
         - ikramulkayes
         - Imtiaz1234
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for es contents only
  - name: dev-es
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # es approvers
        users:
         - raelga
         - electrocucaracha
         - krol3
         - 92nqb
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for zh contents only
  - name: dev-zh
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # zh approvers
        users:
         - hanyuancheung
         - Jacob953
         - Rocksnake
         - Submarinee
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for fr contents only
  - name: dev-fr
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # fr approvers
        users:
         - huats
         - fydrah
         - Krast76
        teams: []
      enforce_admins: null
      required_linear_history: null
      
  # l10n branch for ur contents only
  - name: dev-ur
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # ur approvers
        users:
         - Saim-Safdar
         - waleed318
        teams: []
      enforce_admins: null
      required_linear_history: null
