# Get more info on the settings.yaml here:https://github.com/apps/settings
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: glossary

  # A short description of the repository that will show up on GitHub
  description: Cloud Native Glossary

  # A URL with more information about the repository
  homepage: https://glossary.cncf.io/
  
  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Chairs
  - username: caniszczyk
    permission: admin

  - username: jasonmorgan
    permission: admin

  - username: CathPag
    permission: maintain
    
  - username: seokho-son
    permission: admin

  # l10n ko approvers
  # Note: seokho-son is both a maintainer (maintain) and Korean approver (push)
  - username: jihoon-seo
    permission: push

  - username: Eviekim
    permission: push

  # l10n pt approvers
  - username: edsoncelio
    permission: push

  - username: brunoguidone
    permission: push

  # l10n hi approvers
  - username: Garima-Negi
    permission: push

  - username: sayantani11
    permission: push

  - username: anubha-v-ardhan
    permission: push

  - username: jayesh-srivastava
    permission: push

  # l10n de approvers
  # Note: CathPag is both a maintainer (maintain) and de approver (push)
  - username: iamNoah1
    permission: push

  # l10n it approvers
  - username: Giulia-dipietro
    permission: push

  - username: meryem-ldn
    permission: push

  - username: annalisag-spark
    permission: push

  - username: sistella
    permission: push

  # l10n ar approvers

  # l10n bn approvers


branches:

  # Default branch of this repository for configurations and English contents
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # En approvers (including Chairs)
        users:
         - caniszczyk
         - jasonmorgan
         - CathPag
         - seokho-son
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for Korean contents only
  - name: dev-ko
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # Ko approvers
        users:
         - seokho-son
         - Eviekim
         - jihoon-seo
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for pt contents only
  - name: dev-pt
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # pt approvers
        users:
         - edsoncelio
         - brunoguidone
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for hi contents only
  - name: dev-hi
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # hi approvers
        users:
         - Garima-Negi
         - sayantani11
         - anubha-v-ardhan
         - jayesh-srivastava
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for de contents only
  - name: dev-de
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # de approvers
        users:
         - CathPag
         - iamNoah1
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for it contents only
  - name: dev-it
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # it approvers
        users:
         - Giulia-dipietro
         - meryem-ldn
         - annalisag-spark
         - sistella
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for ar contents only
  - name: dev-ar
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # ar approvers
        users:
         - seokho-son
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for bn contents only
  - name: dev-bn
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # bn approvers
        users:
         - seokho-son
        teams: []
      enforce_admins: null
      required_linear_history: null
