# Get more info on the settings.yaml here:https://github.com/apps/settings
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: glossary

  # A short description of the repository that will show up on GitHub
  description: Cloud Native Glossary

  # A URL with more information about the repository
  homepage: https://glossary.cncf.io/
  
  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Chairs
  - username: caniszczyk
    permission: admin

  - username: jasonmorgan
    permission: admin

  - username: CathPag
    permission: maintain
    
  - username: seokho-son
    permission: admin

  # l10n ko approvers
  # Note: seokho-son is both a maintainer (maintain) and Korean approver (push)
  - username: jihoon-seo
    permission: push

  - username: Eviekim
    permission: push

  # l10n pt approvers
  - username: edsoncelio
    permission: push

  - username: brunoguidone
    permission: push
    
branches:

  # Default branch of this repository for configurations and English contents
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # En approvers (including Chairs)
        users:
         - caniszczyk
         - jasonmorgan
         - CathPag
         - seokho-son
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for Korean contents only
  - name: dev-ko
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # Ko approvers
        users:
         - seokho-son
         - Eviekim
         - jihoon-seo
        teams: []
      enforce_admins: null
      required_linear_history: null

  # l10n branch for pt contents only
  - name: dev-pt
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # pt approvers
        users:
         - edsoncelio
         - brunoguidone
        teams: []
      enforce_admins: null
      required_linear_history: null

