[build]
publish = "public"
command = "make production-build"

[build.environment]
NODE_VERSION = "22"
HUGO_VERSION = "0.146.0"
GO_VERSION = "1.22"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_ENV = "preview"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"