---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Spellcheck CI
# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'content/es/**/*.md'
    branches:
      - dev-es
  workflow_dispatch:

jobs:
  check-spanish-spellcheck:
    name: Run PySpelling tool to verify spanish spelling issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.29.0
        with:
          config_path: content/es/.spellcheck.yml
