name: "Stale label"
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 12am UTC
  push:
    branches:
      - 'dev-es'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    timeout-minutes: 1 # Default: 360 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue/PR is stale because it has been inactive for 60 days. This issue/PR will be closed automatically with additional 20 days of inactivity. If an update/comment occur on stale issue/PR, the stale label will be removed and the timer will restart. Closed issue/PR can be reopened if necessary.'
        stale-pr-message: 'This issue/PR is stale because it has been inactive for 60 days. This issue/PR will be closed automatically with additional 20 days of inactivity. If an update/comment occur on stale issue/PR, the stale label will be removed and the timer will restart. Closed issue/PR can be reopened if necessary.'
        exempt-issue-labels: 'maintainers, lang/es'
        exempt-pr-labels: 'maintainers'
        stale-pr-label: 'stale'
        stale-issue-label: 'stale'
        days-before-stale: 60
        days-before-close: 20
        only-labels: 'lang/es'
        close-issue-label: 'close/stale'
        close-pr-label: 'close/stale' # Add the label for mainteiners track the close pr labels.